global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Мониторинг самого Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Мониторинг ML сервиса
  - job_name: 'ml_service'
    static_configs:
      - targets: ['ml_service:8000']  # имя сервиса из docker-compose
        labels:
          service: 'car-price-predictor'
          version: '3'
    scrape_interval: 10s
    metrics_path: '/metrics'